[variables]
ASPNETCORE_ENVIRONMENT = 'Production'
ASPNETCORE_URLS = 'http://0.0.0.0:3000'
DOTNET_ROOT = '/nix/var/nix/profiles/default/'
NIXPACKS_CSHARP_SDK_VERSION = '8'
NIXPACKS_METADATA = 'c#'
Destiny__ApiKey=''
Destiny__ClientID=''
Destiny__ClientSecret=''
Destiny__NetworkClans='[]'
Discord__AdminRoles='[]'
Discord__BotToken=''
Discord__ClientID=''
Discord__ClientSecret=''
Discord__ModeratorRoles='[]'
Discord__RedirectUrl=''
Discord__TargetServers='[]'
Logging__LogLevel__Default='Information'
Logging__LogLevel__Microsoft__AspNetCore='Warning'

[phase.name]
nixpkgsArchive = "a45fa362d887f4d4a7157d95c28ca9ce2899b70e"


[phases.build]
dependsOn = ['install']
cmds = ['dotnet publish --no-restore -c Release -o ./out']

[phases.install]
dependsOn = ['setup']
cmds = ['dotnet restore']

[phases.setup]
nixPkgs = ['dotnet-sdk']
nixOverlays = []
nixpkgsArchive = "a45fa362d887f4d4a7157d95c28ca9ce2899b70e"

[start]
cmd = 'cd out && dotnet auth-server.dll' 